Reduce memory occupation in generating hash
DLTcollab/hashchain pull request #6
Opened 2019-12-12 14:33 UTC by afcidk

Fixes #5.

The original implementation stores the generated hash in seperated
memory regions, which may lead to program crash.

I'll print the hash immediately instead of saving the hashes.

Generating hash with indicating index is also supported now using
`./hashchain create ALGO OFFSET SIZE SEED` format.

2019-12-13 03:43 UTC, howjmay requested changes

2019-12-13 03:43 UTC, HowJMay commented on README.md
> +$ ./hashchain create sha256 1 10 "my secret password"
I think the naming `OFFSET` may not be really proper here.
If the value `OFFSET` starts from 1, then it feels much more like `INDEX` but not `OFFSET`.
If it is `OFFSET`, then I think the value of `OFFSET` should start from `0`

2019-12-13 08:11 UTC, jserv commented on README.md
> +$ ./hashchain create ALGORITHM INDEX SIZE SEED
I am afraid of the  confusion caused by variant argument counts and sequence of given values. Can we introduce getopt to parse something like `-a ALGORITHM`, `-i INDEX`, `-s SIZE`, etc.?

2019-12-21 08:52 UTC, HowJMay commented on hashchain.c
> +        EVP_DigestFinal_ex(ctx, output.data, NULL);
Are we able to merge the two loop from `line 74` to `line 85` together?

2020-01-01 17:35 UTC, jserv commented
@afcidk, per @HowJMay requested, can you rework?

2020-01-01 17:56 UTC, merged